
name: SQL Linter

on:
  push:
    branches: [main]

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Start JSON Linter
        run: |
          npm i -g @prantlf/jsonlint
          jsonlint $GITHUB_WORKSPACE/DataSchemaModified.json
